"""SQLAlchemy 2.0 declarative base, naming conventions and reusable mixins.

Architecture note
-----------------
A strict constraint naming convention is configured here.  Without it Alembic
generates anonymous constraint names that differ between environments, which
makes autogenerated down-migrations unreliable.  With it every index, unique
key, foreign key and check constraint has a deterministic name.
"""

from __future__ import annotations

from datetime import UTC, datetime
from enum import Enum
from typing import Any

from sqlalchemy import BigInteger, DateTime, Integer, MetaData, func
from sqlalchemy.engine import Dialect
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column
from sqlalchemy.types import TypeDecorator

NAMING_CONVENTION: dict[str, str] = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


def enum_values(enum_cls: type[Enum]) -> list[str]:
    """Persist enum *values* (``"youtube"``) instead of names (``"YOUTUBE"``).

    SQLAlchemy stores ``Enum.name`` by default, which would put shouting
    identifiers in the database and break any hand-written SQL that compares
    against the API/JSON representation.  Every ``SAEnum`` column passes this
    helper as ``values_callable`` so the stored form matches the domain value.
    """
    return [member.value for member in enum_cls]


def utcnow() -> datetime:
    """Timezone-aware "now" used as a Python-side default."""
    return datetime.now(UTC)


class Base(DeclarativeBase):
    """Declarative base shared by every ORM model."""

    metadata = MetaData(naming_convention=NAMING_CONVENTION)

    def as_dict(self, *, exclude: set[str] | None = None) -> dict[str, Any]:
        """Shallow dict of column values — handy for API/admin serialisation."""
        excluded = exclude or set()
        return {
            column.name: getattr(self, column.name)
            for column in self.__table__.columns
            if column.name not in excluded
        }

    def __repr__(self) -> str:  # pragma: no cover - debugging helper
        pk = getattr(self, "id", None)
        return f"<{type(self).__name__} id={pk}>"


class UtcDateTime(TypeDecorator[datetime]):
    """``TIMESTAMPTZ`` that always hands Python a timezone-aware UTC value.

    PostgreSQL returns aware datetimes, SQLite (used by the test-suite) returns
    naive ones, and a naive/aware comparison raises ``TypeError`` at runtime.
    Normalising in one place removes that whole class of bugs and guarantees
    that a naive value can never be written either.
    """

    impl = DateTime(timezone=True)
    cache_ok = True

    def process_bind_param(self, value: datetime | None, dialect: Dialect) -> datetime | None:
        if value is None:
            return None
        return value.replace(tzinfo=UTC) if value.tzinfo is None else value.astimezone(UTC)

    def process_result_value(self, value: datetime | None, dialect: Dialect) -> datetime | None:
        if value is None:
            return None
        return value.replace(tzinfo=UTC) if value.tzinfo is None else value.astimezone(UTC)


#: SQLite only auto-increments a column declared exactly ``INTEGER PRIMARY KEY``
#: (the rowid alias), so the 64-bit type is swapped for the test dialect.  On
#: PostgreSQL this still produces ``BIGSERIAL``.
_SURROGATE_PK = BigInteger().with_variant(Integer, "sqlite")


class IntPKMixin:
    """64-bit auto-increment surrogate primary key."""

    id: Mapped[int] = mapped_column(_SURROGATE_PK, primary_key=True, autoincrement=True)


class TimestampMixin:
    """``created_at`` / ``updated_at`` maintained by the database."""

    created_at: Mapped[datetime] = mapped_column(
        UtcDateTime,
        server_default=func.now(),
        nullable=False,
        index=True,
    )
    updated_at: Mapped[datetime] = mapped_column(
        UtcDateTime,
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )
