"""The Alembic migration must produce a schema that actually accepts writes.

These tests exist because ``Base.metadata.create_all`` (what the other tests
use) and ``alembic upgrade head`` are two different code paths: the first one
resolved SQLite's ``INTEGER PRIMARY KEY`` requirement through a dialect
variant, the migration originally did not, and inserts failed only in the
standalone (Termux) deployment.
"""

from __future__ import annotations

import sqlite3
from pathlib import Path

import pytest

pytestmark = pytest.mark.integration

alembic_command = pytest.importorskip("alembic.command")
from alembic.config import Config  # noqa: E402

PROJECT_ROOT = Path(__file__).resolve().parents[2]


@pytest.fixture
def alembic_config(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> Config:
    """An Alembic config pointing at a throw-away SQLite file."""
    database = tmp_path / "migration-test.db"
    monkeypatch.setenv("DB__URL_OVERRIDE", f"sqlite:///{database}")
    monkeypatch.setenv("MEDIABOT_ENV_FILE", "/dev/null")

    from mediabot.core.config import get_settings

    get_settings.cache_clear()
    config = Config(str(PROJECT_ROOT / "alembic.ini"))
    config.set_main_option("script_location", str(PROJECT_ROOT / "migrations"))
    config.attributes["database_path"] = str(database)
    yield config
    get_settings.cache_clear()


def _database_path(config: Config) -> Path:
    return Path(str(config.attributes["database_path"]))


class TestInitialMigration:
    def test_upgrade_creates_every_table(self, alembic_config: Config) -> None:
        alembic_command.upgrade(alembic_config, "head")

        connection = sqlite3.connect(_database_path(alembic_config))
        try:
            tables = {
                row[0]
                for row in connection.execute("SELECT name FROM sqlite_master WHERE type='table'")
            }
        finally:
            connection.close()

        expected = {
            "users",
            "user_limits",
            "wallets",
            "transactions",
            "referrals",
            "achievements",
            "languages",
            "downloads",
            "download_queue",
            "download_history",
            "favorites",
            "favorite_collections",
            "subscriptions",
            "payments",
            "promo_codes",
            "promo_activations",
            "notifications",
            "admins",
            "audit_logs",
            "error_logs",
            "settings",
            "statistics",
        }
        assert expected <= tables

    def test_surrogate_keys_auto_increment_on_sqlite(self, alembic_config: Config) -> None:
        """The regression: ``BIGINT`` primary keys are not auto-increment in SQLite."""
        alembic_command.upgrade(alembic_config, "head")

        connection = sqlite3.connect(_database_path(alembic_config))
        try:
            connection.execute(
                "INSERT INTO admins (username, password_hash, role, is_active, failed_logins) "
                "VALUES ('root', 'hash', 'owner', 1, 0)"
            )
            connection.commit()
            row = connection.execute("SELECT id, username FROM admins").fetchone()
        finally:
            connection.close()

        assert row[0] == 1, "primary key must be generated by the database"
        assert row[1] == "root"

    def test_foreign_keys_and_indexes_exist(self, alembic_config: Config) -> None:
        alembic_command.upgrade(alembic_config, "head")

        connection = sqlite3.connect(_database_path(alembic_config))
        try:
            foreign_keys = connection.execute("PRAGMA foreign_key_list(downloads)").fetchall()
            indexes = {
                row[0]
                for row in connection.execute("SELECT name FROM sqlite_master WHERE type='index'")
            }
        finally:
            connection.close()

        assert any(fk[2] == "users" for fk in foreign_keys), "downloads must reference users"
        assert "ix_downloads_cache_key" in indexes
        assert "ix_download_queue_priority_enqueued" in indexes

    def test_downgrade_removes_everything(self, alembic_config: Config) -> None:
        alembic_command.upgrade(alembic_config, "head")
        alembic_command.downgrade(alembic_config, "base")

        connection = sqlite3.connect(_database_path(alembic_config))
        try:
            remaining = {
                row[0]
                for row in connection.execute("SELECT name FROM sqlite_master WHERE type='table'")
            }
        finally:
            connection.close()

        # Only Alembic's own bookkeeping table survives a full downgrade.
        assert remaining <= {"alembic_version"}
